# Generated by Django 5.2.8 on 2025-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0034_speakerprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerprofile",
            name="name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="speakerprofile",
            name="name_parts",
            field=models.JSONField(default=dict),
        ),
    ]
