# Generated by Django 5.2.8 on 2025-11-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0086_alter_question_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerrole",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
