# Generated by Django 5.2.8 on 2025-11-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0086_alter_question_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="max_choices",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="min_choices",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
