# Generated by Django 5.2.8 on 2025-11-17 18:25

import django.db.models.deletion
import pretalx.common.models.mixins
import pretalx.submission.models.invitation
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0086_alter_question_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.CharField(
                        default=pretalx.submission.models.invitation.generate_invite_token,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="submission.submission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "email")},
            },
            bases=(
                pretalx.common.models.mixins.LogMixin,
                pretalx.common.models.mixins.FileCleanupMixin,
                rules.contrib.models.RulesModelMixin,
                models.Model,
            ),
        ),
    ]
