# Generated by Django 5.2.8 on 2025-11-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0086_alter_question_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allowed_file_types",
            field=models.JSONField(default=list),
        ),
    ]
