codecov:
  notify:
    require_ci_to_pass: yes
  ci:
    - runner.rixx.de
    - !travis-ci.org

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    threshold: 2%
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  require_changes: yes
  layout: "header, diff, files"
  behavior: default
