# Generated by Django 5.2.8 on 2025-11-17 23:11

import pretalx.event.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0040_alter_event_settingsstore_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="social_preview_settings",
            field=models.JSONField(
                default=pretalx.event.models.event.default_social_preview_settings
            ),
        ),
    ]
