---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: pretalx
    type: pull-request
    webhook_token: ooshiecalee4eaghi8eiweM5ciejaisu
    check_every: 1h
    source:
      repository: rixx/pretalx
      disable_forks: false
      access_token: ((pretalx_access_token))

jobs:
  - name: test
    public: true
    plan:
      - get: pretalx
        trigger: true
        version: every
      - put: pretalx
        params:
          path: pretalx
          status: pending
      - task: Run tests
        file: pretalx/ci/pretalx-tests.yml
        vars:
          codecov: ((codecov_token))
          python-version: 3.7
    on_failure:
      put: pretalx
      params:
        path: pretalx
        status: failure
  - name: lint
    public: true
    plan:
      - get: pretalx
        trigger: true
        version: every
      - task: Run lint
        file: pretalx/ci/pretalx-lint.yml
    on_failure:
      put: pretalx
      params:
        path: pretalx
        status: failure
  - name: docs
    public: true
    plan:
      - get: pretalx
        trigger: true
        version: every
      - task: build docs
        file: pretalx/ci/pretalx-docs.yml
    on_failure:
      put: pretalx
      params:
        path: pretalx
        status: failure
  - name: github
    plan:
      - put: pretalx
        passed:
          - test
          - lint
          - docs
        params:
          path: pretalx
          status: success
