---
resources:
  - name: pretalx
    type: git
    source: &repo-source
      uri: https://github.com/rixx/pretalx
      branch: master

jobs:
  - name: test
    public: true
    plan:
      - get: pretalx
        trigger: true
      - in_parallel:
        - task: Run tests for Python 3.6
          file: pretalx/ci/pretalx-tests.yml
          vars:
            codecov:
            python_version: 3.6
        - task: Run tests for Python 3.7
          file: pretalx/ci/pretalx-tests.yml
          vars:
            codecov: ((codecov_token))
            python_version: 3.7
        - task: Run tests for Python 3.8
          file: pretalx/ci/pretalx-tests.yml
          vars:
            codecov:
            python_version: 3.8.0b1
  - name: lint
    public: true
    plan:
      - get: pretalx
        trigger: true
      - task: Run lint
        file: pretalx/ci/pretalx-lint.yml
  - name: docs
    public: true
    plan:
      - get: pretalx
        trigger: true
      - task: build docs
        file: pretalx/ci/pretalx-docs.yml
  - name: deploy
    plan:
      - get: pretalx
        trigger: true
        passed:
          - test
          - lint
          - docs
      - task: Run deploy on next
        file: pretalx/ci/pretalx-deploy.yml
