---
resources:
  - name: pretalx
    type: git
    source: &repo-source
      uri: https://github.com/rixx/pretalx
      tag_filter: "v*"

jobs:
  - name: test
    public: true
    plan:
      - get: pretalx
        trigger: true
      - task: Run tests
        file: pretalx/ci/pretalx-tests.yml
        vars:
          codecov: ((codecov_token))
          python-version: 3.7
  - name: deploy
    plan:
      - get: pretalx
        trigger: true
        passed:
          - test
      - task: Deploy the pretalx package
        file: pretalx/ci/pretalx-package.yml
        vars:
          twine_user: ((twine_user))
          twine_password: ((twine_password))
