#!/bin/bash
ls
pwd
python --version
which pip

apt-get update
apt-get install gettext-base
apt-cache search gettext

cd pretalx/src
pip install -e ".[dev]"
cd ../doc
pip install -r requirements.txt

make html
make linkcheck
