#!/bin/bash

set -e

apt-get update
apt-get -y install locales gettext enchant myspell-en-gb
locale-gen de_DE

cd pretalx/src
pip install -e ".[dev]"

cd ..
pip install -r doc/requirements.txt

cd doc

make html
make linkcheck
