#!/bin/bash

set -e

apt-get update
apt-get -y install locales gettext
locale-gen de_DE

cd pretalx/src
pip install -e ".[dev]"

echo "First positional argument"
echo "$1"
if [[ "$1" == "push" ]]; then
    python -m pretalx rebuild
    pip install codecov coverage
    pytest --cov=pretalx
    codecov
else
    pytest
fi
