#!/bin/bash

set -e

apt-get update
apt-get -y install locales gettext
locale-gen de_DE

cd pretalx/src
pip install -e ".[dev]"

echo "First positional argument"
echo "$1"

python -m pretalx rebuild

if [[ "$1" != "" ]]; then
    pip install codecov coverage
    pytest --cov=pretalx
    codecov --token="$1"
else
    pytest
fi
